name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - seaborn
  - scipy
  - statsmodels
  - plotly
  - pandas
  - matplotlib
  - scikit-learn
  - numpy

